# Homework1 - datatalks.club

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Q1. Pandas version

What's the version of Pandas that you installed?

In [39]:
pd.__version__

'2.1.3'

### Getting Data

In [40]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
!curl -O https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  291k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  291k  100  291k    0     0   968k      0 --:--:-- --:--:-- --:--:--  978k


## Q2. Records count

How many records are in the dataset?

In [41]:
df = pd.read_csv('laptops.csv')

df.shape

(2160, 12)

## Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [42]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [43]:
df['Brand'].nunique()

27

## Q4. Missing values
How many columns in the dataset have missing values?

In [44]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [45]:
print("The number of columns with missing values is: ", df.isna().any().sum())

The number of columns with missing values is:  3


## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [46]:
df[df['Brand'] == 'Dell'].sort_values('Final Price', ascending=False).head(5)

Laptop       Status Brand  \
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...          New  Dell   
1334  Dell Precision 5470 Intel Core i7-12800H/16GB/...          New  Dell   
1346  Dell XPS 15 9520 Intel Core i7-12700H/16GB RAM...          New  Dell   
1347  Dell XPS 15 9520 Intel Core i7-12700H/32GB/1TB...  Refurbished  Dell   
1323  Dell Latitude 5520 Intel Core i5-1135G7/8GB/25...          New  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   
1334  Precision  Intel Core i7   16      512          SSD  RTX A1000    14.0   
1346        XPS  Intel Core i7   16     1000          SSD   RTX 3050    15.6   
1347        XPS  Intel Core i7   32     1000          SSD   RTX 3050    15.6   
1323   Latitude  Intel Core i5    8      256          SSD        NaN    15.6   

     Touch  Final Price  
1335   Yes      3936.00  
1334    No      3469.00  
1346    No      3012.09  
1347   Yes      2818.09  
1323    No      2450.71

In [47]:
print("The most expensive Dell laptop is: ", df[df['Brand'] == 'Dell'].sort_values('Final Price', ascending=False).head(1)["Final Price"].values[0])

The most expensive Dell laptop is:  3936.0


## Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.


Has it changed?

Yes
No

In [48]:
df['Screen'].isna().sum() #four missing values

4

In [49]:
print(f"The median value of Screen is: {df['Screen'].median()}")
print(f"The most frequent value of Screen is: {df['Screen'].mode()[0]}")

#filling the missing values with the most frequent value
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)

print(f"The median value of screen after filling the missing values is: {df['Screen'].median()}")

The median value of Screen is: 15.6
The most frequent value of Screen is: 15.6
The median value of screen after filling the missing values is: 15.6


In [50]:
# double check if we have any missing values
df['Screen'].isna().sum()

0

In [51]:
print("The value has not change after filling the missing values")

The value has not change after filling the missing values


## Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [57]:
# steps 1,2,3
X = np.array(df[df['Brand'] == "Innjoo"][['RAM', 'Storage','Screen']])

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [58]:
# step 4 - compute X transpose and X
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [59]:
# step 5 - compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [60]:
# step 6 - create and array y
y = np.array([1100,1300,800,900,1000,1100])


In [62]:
# step 7 - multiply inverse of XTX with X and then multiple the result with y - w

w = XTX_inv.dot(X.T).dot(y)

print(f"The weights are: {w}")

The weights are: [45.58076606  0.42783519 45.29127938]


In [63]:
# step 8 - sum of weights
print(f"The sum of weights is: {sum(w)}")

The sum of weights is: 91.2998806299555
